apiVersion: syftbox.openmined.org/v1alpha1
kind: Flow
metadata:
  name: 02_bv_paper_hgp1k_projection_fast
  version: 0.2.1
spec:
  inputs:
    samplesheet:
      type: List[GenotypeRecord]
  steps:
    - id: hgp1k_projection_fast
      uses: ./
      with:
        participants: inputs.samplesheet
      publish:
        scores: File(pca_scores.tsv)
        study_projection_tsv: File(study_pca_projection.tsv)
        allele_freqs: File(allele_freqs.tsv)
        qc_report: File(qc_report.txt)
        projection_plot: File(pca_projection.png)
        errors: File(errors.tsv)
        closest_population_labels: File(closest_population_labels.tsv)
        closest_population_summary: File(closest_population_summary.tsv)
        pca_variants_used: File(pca_variants_used.tsv)
        pca_variants_dropped: File(pca_variants_dropped.tsv)
