apiVersion: syftbox.openmined.org/v1alpha1
kind: Flow
metadata:
  name: 01_bv_paper_pca_qc_fast
  version: 0.2.2
spec:
  inputs:
    samplesheet:
      type: List[GenotypeRecord]
  steps:
    - id: pca_qc_fast
      uses: ./
      with:
        participants: inputs.samplesheet
      publish:
        eigenvec: File(pca.eigenvec)
        eigenval: File(pca.eigenval)
        pca_plot_points: File(pca_plot_points.tsv)
        snp_info: File(snp_info.tsv)
        pca_prefiltered_snps: File(pca_prefiltered_snps.tsv)
        filtered_snps: File(filtered_snps.tsv)
        pca_pc12_plot: File(pca_pc1_pc2.png)
        pca_pc34_plot: File(pca_pc3_pc4.png)
        pipeline_log: File(fast_pipeline.log)
